### ISSUE TITLE
Self-contained bash build for Ubuntu

### ISSUE THREAD

**Issue by wankdanker** [k3d3/claude-desktop-linux-flake#2]
Great work on this project! Claude helped build this self-contained bash script (which includes some of your lib.rs). It works fine on Ubuntu. Doesn't install to a system package, but builds to the repo dir and you can just execute it.

https://github.com/wankdanker/claude-desktop-linux-bash

**Comment by k3d3** [comment]
That looks fantastic, thank you! 

One note:
> The script creates stub implementations for the native functions, which means some features might not work (like global shortcuts)

Global shortcuts (namely the Ctrl-Alt-Space popup) actually do still work, however it only works when running it under X11.

While Wayland as a protocol *technically* supports global shortcuts, it's still brand new and basically nobody has implemented it - sadly, Electron is no exception.

Otherwise this looks great! I'll add it to the README.

**Comment by wankdanker** [comment]
Thank you for reviewing and thank you for the information about Wayland and X11. The line you quoted was written by Claude :) I'll give it an update though with your additional context.

Thanks so much! I hope someone finds this useful. :)
